### ISSUE TITLE
can you provide the SMILES of compound in dataset？

### ISSUE THREAD

**Issue by piaoyang1992** [ChendiHan111/MCFF-MTDDI#1]
thanks for your work, can you provide the SMILES of compound in dataset？

**Comment by Robotjimit** [comment]
hello,I have a problem 
Traceback (most recent call last):
  File "multi-class-prediction1.py", line 415, in <module>
    drug_emb4 = feature_vector(filename[4], drugs)
  File "multi-class-prediction1.py", line 43, in feature_vector
    feature[eval(d)]=eval(emb)
  File "<string>", line 1
    Compound::DB00001
            ^
SyntaxError: invalid syntax
do you solve it?

**Comment by jiajieshidongjuncheng** [comment]
> hello,I have a problem Traceback (most recent call last): File "multi-class-prediction1.py", line 415, in drug_emb4 = feature_vector(filename[4], drugs) File "multi-class-prediction1.py", line 43, in feature_vector feature[eval(d)]=eval(emb) File "", line 1 Compound::DB00001 ^ SyntaxError: invalid syntax do you solve it?

i meet this problem too.

**Comment by jiajieshidongjuncheng** [comment]
Can anyone **successfully** run this code?
